# Generated by Django 5.1.2 on 2024-12-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_remove_profile_account_number_remove_profile_balance_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="profile",
            name="account_number",
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
