# Generated by Django 5.1.2 on 2024-12-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_remove_profile_address_remove_profile_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
