# Generated by Django 5.1.2 on 2024-12-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_transaction_description_alter_transaction_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="description",
        ),
    ]
